name: NPM-CI
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: yarn install
      - name: Build Declaration
        run: yarn build:type
      - name: Build ES5 code
        run: yarn build
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_USER: ${{secrets.AUTHOR_NAME}}
          GITHUB_EMAIL: ${{secrets.AUTHOR_EMAIL}}
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

