name: NPM-CI
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v7.1.0
        env:
          GITHUB_USER: ${{secrets.AUTHOR_NAME}}
          GITHUB_EMAIL: ${{secrets.AUTHOR_EMAIL}}
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
