name: NPM-CI
on:
  push:
    branches: 
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org
    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@master
      env:
        GITHUB_USER: ${{secrets.AUTHOR_NAME}}
        GITHUB_EMAIL: ${{secrets.AUTHOR_EMAIL}}
    - name: Install Dependencies
      working-directory: ./template
      run: yarn install 
    - name: Build 
      working-directory: ./template
      run: yarn build
    - name: Delploy
      working-directory: ./template/build
      run: yarn global add surge && surge . ${{secrets.SURGE_DOMAIN}} --token ${{secrets.SURGE_TOKEN}}
