name: publish
on:
  push:
    branches:
      - main
      - dev
env:
  CI: true
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: Install dependencies
        run: |
          npm install yarn -g
          yarn install
      - name: Publish NPM
        run: |
          npm run build
          npm run publish